services:
  db:
    image: postgres:16.4-alpine
    container_name: ${PROJECT_NAME:-inchfab}-postgresdb-${ENVIRONMENT}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USER} -d ${POSTGRES_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - inchfab-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongodb:
    image: mongo:7.0.15-jammy
    container_name: ${PROJECT_NAME:-inchfab}-mongodb-${ENVIRONMENT}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASS}
      MONGO_DB_USER: ${MONGO_DB_USER}
      MONGO_DB_PASS: ${MONGO_DB_PASS}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
      - ./init-mongo-user.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped
    command: ["--auth", "--bind_ip_all"]
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping").ok' --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - inchfab-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  api:
    container_name: ${PROJECT_NAME:-inchfab}-api-${ENVIRONMENT}
    image: ${DOCKER_USERNAME}/inchfab-api:${APP_VERSION:-latest}
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      TZ: Asia/Singapore
      PROJECT_NAME: ${PROJECT_NAME:-InchFab}
      ACTIVE_PROFILE: ${ENVIRONMENT}

      POSTGRES_DB_URI: jdbc:postgresql://db:5432/${POSTGRES_DB_NAME}
      POSTGRES_DB_USER: ${POSTGRES_DB_USER}
      POSTGRES_DB_PASS: ${POSTGRES_DB_PASS}

      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASS}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin

      AUTH0_ISSUER: ${AUTH0_ISSUER}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}

      BOX_CLIENT_ID: ${BOX_CLIENT_ID}
      BOX_CLIENT_SECRET: ${BOX_CLIENT_SECRET}
      BOX_ENTERPRISE_ID: ${BOX_ENTERPRISE_ID}
      BOX_FOLDER_ID: ${BOX_FOLDER_ID}

      JAVA_OPTS: >
        -XX:+UseG1GC
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/var/log/dump.hprof
        -XX:MaxRAMPercentage=75.0
        -XX:InitialRAMPercentage=50.0
        -XX:+UseContainerSupport
        -XX:+ExitOnOutOfMemoryError
        -Djava.security.egd=file:/dev/./urandom
        -Dfile.encoding=UTF-8
    volumes:
      - ./logs:/var/log
    networks:
      - inchfab-network
    depends_on:
      db:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    pull_policy: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  inchfab-network:
    driver: bridge
    name: ${PROJECT_NAME:-inchfab}-network-${ENVIRONMENT}

volumes:
  pg_data:
    name: ${PROJECT_NAME:-inchfab}-postgres-${ENVIRONMENT}
  mongo_data:
    name: ${PROJECT_NAME:-inchfab}-mongodb-${ENVIRONMENT}
  mongo_config:
    name: ${PROJECT_NAME:-inchfab}-mongodb-config-${ENVIRONMENT}

configs:
  docker_auth:
    file: ${DOCKER_CONFIG:-~/.docker}/config.json

secrets:
  docker_auth:
    file: ${DOCKER_CONFIG:-~/.docker}/config.json