-- Set timezone to UTC
SET TIME ZONE 'UTC';

-- Companies table
CREATE TABLE "companies"
(
    "id"    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"  VARCHAR(255) UNIQUE NOT NULL,
    "logo"  VARCHAR(512), -- Assuming this stores a URL/path
    "email" VARCHAR(255) CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
) ,
    "title"      VARCHAR(255),
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Add trigger for updated_at
CREATE
OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at
= CURRENT_TIMESTAMP;
RETURN NEW;
END;
$$
language 'plpgsql';

CREATE TRIGGER update_companies_updated_at
    BEFORE UPDATE
    ON companies
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Projects table
CREATE TABLE "projects"
(
    "id"                                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "company_id"                        INTEGER                                            NOT NULL,
    "requester_id"                      VARCHAR(255)                                       NOT NULL,
    "submitter_id"                      VARCHAR(255)                                       NOT NULL,
    "requester_name"                    VARCHAR(255)                                       NOT NULL,
    "submitter_name"                    VARCHAR(255)                                       NOT NULL,
    "root_folder_id"                    VARCHAR(255),
    "project_folder_id"                 VARCHAR(255),
    "upload_file"                       VARCHAR(512), -- Assuming this stores a file path/URL
    "name"                              VARCHAR(255)                                       NOT NULL,
    "wafer_size"                        INTEGER CHECK (wafer_size > 0),
    -- Using DECIMAL(15,2) for monetary values to ensure precision
    "labor_cost"                        DECIMAL(15, 2)           DEFAULT 0.00 CHECK (labor_cost >= 0),
    "electrical_cost"                   DECIMAL(15, 2)           DEFAULT 0.00 CHECK (electrical_cost >= 0),
    "substrate_type"                    VARCHAR(100),
    "total_time"                        DECIMAL(10, 2)           DEFAULT 0.00 CHECK (total_time >= 0),
    "total_time_cost"                   DECIMAL(15, 2)           DEFAULT 0.00 CHECK (total_time_cost >= 0),
    "total_labor_cost"                  DECIMAL(15, 2)           DEFAULT 0.00 CHECK (total_labor_cost >= 0),
    "total_periodic_cost"               DECIMAL(15, 2)           DEFAULT 0.00 CHECK (total_periodic_cost >= 0),
    "total_power_cost"                  DECIMAL(15, 2)           DEFAULT 0.00 CHECK (total_power_cost >= 0),
    "total_gas_cost"                    DECIMAL(15, 2)           DEFAULT 0.00 CHECK (total_gas_cost >= 0),
    "total_target_material_cost"        DECIMAL(15, 2)           DEFAULT 0.00 CHECK (total_target_material_cost >= 0),
    "total_wet_etchant_cost"            DECIMAL(15, 2)           DEFAULT 0.00 CHECK (total_wet_etchant_cost >= 0),
    "total_lithography_reagent_cost"    DECIMAL(15, 2)           DEFAULT 0.00 CHECK (total_lithography_reagent_cost >= 0),
    "total_metrology_inspection_cost"   DECIMAL(15, 2)           DEFAULT 0.00 CHECK (total_metrology_inspection_cost >= 0),
    "total_external_process_cost"       DECIMAL(15, 2)           DEFAULT 0.00 CHECK (total_external_process_cost >= 0),
    "total_manually_input_process_cost" DECIMAL(15, 2)           DEFAULT 0.00 CHECK (total_manually_input_process_cost >= 0),
    "total_substrate_cost"              DECIMAL(15, 2)           DEFAULT 0.00 CHECK (total_substrate_cost >= 0),
    "project_step"                      JSON,
    "status"                            BOOLEAN                  DEFAULT false             NOT NULL,
    "created_at"                        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updated_at"                        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_company
        FOREIGN KEY ("company_id")
            REFERENCES "companies" ("id")
            ON DELETE RESTRICT
);

CREATE TRIGGER update_projects_updated_at
    BEFORE UPDATE
    ON projects
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Create indexes for better query performance
CREATE INDEX idx_projects_company_id ON projects (company_id);
CREATE INDEX idx_projects_status ON projects (status);
CREATE INDEX idx_projects_created_at ON projects (created_at);